### ISSUE TITLE
What are the known issues with supporting Windows?

### ISSUE THREAD

**Issue by zacbrown** [tcolar/goed#111]
I primarily work on Windows and develop on Windows. I might be interested in fixing the Windows-specific issues.

**Comment by tcolar** [comment]
Hey Zac,
The main two things, off my head would be:
- it makes assumptions about having a POSIX system (might work say in cygwin but not sure).
- it's meant to run in a terminal, not saying windows doesn't have one, but haven't tested that at all.
- I'm working on a GUI as well (very basic terminal like GUI) because terminal events support tends to be all over the place .... this is still very much work in progress (event branch), but there might be more hope there for windows.
- Embedded terminal support makes assumptions that there is PTY support, bash and env variables like $PWD and the like ....

But feel free to LMK what you find out or submit a PR.  You might want to use the "event" branch which is much further along and hopefully will be merged into master soon-ish, but in any case it's still fairly alpha and changing quite a bit.

**Comment by tcolar** [comment]
Also  i use kr/pty and I don't believe that supports windows.
